// Generated by Outou from file:///src/formatting-element-between-text. Do not edit.
use outou::prelude::*;

#[component]
fn App() -> Element {
    ::outou::__private::rsx! { div { "a ", b { "x", }, " c", } }
}
