// Generated by Outou from file:///src/formatting-text-then-expression. Do not edit.
use outou::prelude::*;

#[component]
fn App() -> Element {
    let name = "Outou";

    ::outou::__private::rsx! { div { "Hello ", {name}, } }
}
