//! Dioxus backend: lowers the Outou AST to `rsx!` invocations.
//!
//! This crate emits *text*. It does not depend on Dioxus; the runtime is
//! reached at compile time of the user's crate through the hidden path in
//! [`PRIVATE_PATH`], which the `outou` facade re-exports. A user crate
//! therefore never lists Dioxus in its `Cargo.toml`.
//!
//! Children are lowered as separate nodes (`"Hello "` and `{name}`), never
//! folded into a single format string, so that the source map can point at
//! each of them.
//!
//! See `README.md` for the lowering rules and the decisions this crate
//! makes for Phase 0 (recovery placeholders, hyphenated/keyword attribute
//! names, event handlers).

mod attribute;
mod block;
mod element;
mod escape;
mod expr;
mod item;
mod module;
mod recovery;

use outou_codegen::{
    reject_syntax_errors_in_strict_mode, Backend, Error, GenerateOptions, Generated, Mode, Writer,
};
use outou_sourcemap::Span;
use outou_syntax::Parsed;

/// Root path through which generated code reaches the runtime.
pub const PRIVATE_PATH: &str = "::outou::__private";

/// File-level lint allow written at the top of a generated file that
/// needs it, for a mechanical lint that fires on codegen's own output
/// rather than on user code (issue #8's clippy requirement: generated
/// code must not pollute the user's `cargo clippy`). This crate never
/// widens an `allow` beyond what has actually been observed (`AGENTS.md`:
/// "Do not … add `allow` attributes to make them pass" applies to *this*
/// crate's own lints, not to the mechanical Rust it emits for users, which
/// issue #8 explicitly permits scoping an `allow` to).
///
/// Emitted only when [`Writer::marked`] is set after lowering (issue #8
/// fix list step 7) — i.e. only when some attribute island in this
/// specific file actually kept its synthesized braces
/// (`crate::attribute::bare_rust_expr`'s only-when-needed rule strips them
/// everywhere else). A nested-`rsx!` island prop (`icon={<span/>}`) is the
/// one shape that still needs them (stripping breaks `rsx!`'s own
/// parsing — `error: expected identifier` — and no universal brace-free
/// rewrite exists, `docs/backend-leakage.md` row 21).
///
/// This allow *is* file-scoped, and it *does* suppress `unused_braces` on
/// a user's own expression sitting anywhere else in the same file (a
/// corrected claim: an earlier version of this comment said the opposite,
/// disproved by `crates/outou-cli/tests/build_compile.rs`'s `take({ x })`
/// probe).
/// That is an accepted, narrow cost: only files that actually contain a
/// nested-JSX island prop carry the allow at all, and Phase 0 has no
/// narrower attribute-level `#[allow]` available in expression position.
const GENERATED_LINT_ALLOWS: &str = "#![allow(unused_braces)]\n";

/// The Dioxus backend.
#[derive(Debug, Default, Clone, Copy)]
pub struct DioxusBackend;

impl Backend for DioxusBackend {
    fn name(&self) -> &'static str {
        "dioxus"
    }

    fn generate(
        &self,
        parsed: &Parsed,
        source: &str,
        mode: Mode,
        opts: &GenerateOptions,
    ) -> Result<Generated, Error> {
        reject_syntax_errors_in_strict_mode(parsed, mode)?;

        // Whether `GENERATED_LINT_ALLOWS` belongs in the header can only
        // be known once the whole file has been lowered (some attribute
        // island might keep its braces), but the header has to be written
        // *before* the body for every byte offset the source map records
        // to be correct. A first, throwaway lowering pass answers that one
        // question — through the exact same code path as the real pass,
        // so it can never drift out of sync with what that pass actually
        // does — and only the second pass's writer is kept.
        let needs_lint_allow = {
            let mut probe = Writer::new(opts.generated_uri.clone(), opts.source_uri.clone());
            item::lower_items(
                &mut probe,
                source,
                &parsed.file.items,
                opts,
                mode,
                Span::new(0, source.len() as u32),
            );
            probe.marked()
        };

        let mut writer = Writer::new(opts.generated_uri.clone(), opts.source_uri.clone());
        writer.raw("// Generated by Outou from ");
        writer.raw(opts.source_uri.as_str());
        writer.raw(". Do not edit.\n");
        if needs_lint_allow {
            writer.raw(GENERATED_LINT_ALLOWS);
        }
        item::lower_items(
            &mut writer,
            source,
            &parsed.file.items,
            opts,
            mode,
            Span::new(0, source.len() as u32),
        );
        let (rust, source_map) = writer.finish();
        Ok(Generated { rust, source_map })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use outou_codegen::GenerateOptions;
    use outou_sourcemap::Uri;

    fn generate(source: &str, mode: Mode) -> Result<Generated, Error> {
        let parsed = outou_syntax::parse(source);
        let opts = GenerateOptions::new(Uri::new("file:///g.rs"), Uri::new("file:///a.rsx"));
        DioxusBackend.generate(&parsed, source, mode, &opts)
    }

    #[test]
    fn never_mentions_dioxus() {
        let source = "use outou::prelude::*;\n\n#[component]\nfn App() -> Element {\n    <div class=\"x\">Hello {\"world\"}</div>\n}\n";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(!generated.rust.contains("dioxus"), "{}", generated.rust);
    }

    #[test]
    fn strict_mode_rejects_broken_input() {
        let err = generate("fn f() { <div cl", Mode::Strict).unwrap_err();
        assert!(matches!(err, Error::SyntaxErrors { .. }));
    }

    #[test]
    fn simple_component_lowers_to_rsx() {
        let source =
            "#[component]\nfn Greeting(name: String) -> Element {\n    <h1>Hello {name}</h1>\n}\n";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(generated.rust.contains("#[component]"));
        assert!(generated
            .rust
            .contains("fn Greeting(name: String) -> Element"));
        assert!(generated
            .rust
            .contains("::outou::__private::rsx! { h1 { \"Hello \", {name}, } }"));
    }

    /// Issue #8 fix list step 7, decision 4(b): a single bare Rust
    /// expression attribute value lowers without the island's own
    /// synthesized braces, and — since no island in this file needed to
    /// keep them — the file carries no `#![allow(unused_braces)]` at all.
    #[test]
    fn bare_rust_attribute_value_lowers_without_braces_or_the_lint_allow() {
        let source = "fn f() { let x = 1; <div tabindex={x}></div>; }";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(
            generated.rust.contains("tabindex: x,"),
            "{}",
            generated.rust
        );
        assert!(
            !generated.rust.contains("tabindex: {x}"),
            "{}",
            generated.rust
        );
        assert!(
            !generated.rust.contains("unused_braces"),
            "no island in this file needed braces, so no allow is needed:\n{}",
            generated.rust
        );
    }

    /// Same decision, the other half: a nested-JSX island prop keeps its
    /// braces (stripping them breaks `rsx!`'s own parsing, docs/backend-leakage.md
    /// row 21), and the file therefore does carry the allow.
    #[test]
    fn nested_jsx_attribute_value_keeps_its_braces_and_the_lint_allow() {
        let source = "fn f() { <Icon icon={<span></span>}></Icon>; }";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(
            generated
                .rust
                .contains("icon: {::outou::__private::rsx! { span { } }},"),
            "{}",
            generated.rust
        );
        assert!(
            generated.rust.contains("#![allow(unused_braces)]"),
            "a nested-JSX prop keeps its braces, so the file needs the allow:\n{}",
            generated.rust
        );
    }

    #[test]
    fn key_attribute_value_becomes_a_format_string() {
        // HIGH-2, issue #6 fix list item 2: `key={expr}` must lower to
        // `key: "{expr}"`, not the bare island form (`rsx!` rejects the
        // latter with "Key must be in the form of a formatted string").
        let source = "fn f() { let items: Vec<i32> = vec![]; <ul>{items.iter().map(|x| <li key={x.clone()}>{x.clone()}</li>)}</ul>; }";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(
            generated.rust.contains("key: \"{x.clone()}\""),
            "{}",
            generated.rust
        );
        assert!(
            !generated.rust.contains("key: {x.clone()}"),
            "{}",
            generated.rust
        );
    }

    #[test]
    fn key_attribute_value_escapes_embedded_quotes() {
        let source = "fn f() { <li key={x.replace(\"a\", \"b\")}></li>; }";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(
            generated
                .rust
                .contains("key: \"{x.replace(\\\"a\\\", \\\"b\\\")}\""),
            "{}",
            generated.rust
        );
    }

    #[test]
    fn keyword_attribute_on_a_component_uses_a_raw_identifier() {
        // HIGH-3, issue #6 fix list item 3: Dioxus's raw string-key
        // syntax (`"type": value`) only exists for elements; on a
        // component it fails with `no method named 'push_attribute'`.
        // `r#type: value` compiles for both.
        let source = "fn f() { <Field type=\"text\" />; }";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(
            generated.rust.contains("r#type: \"text\""),
            "{}",
            generated.rust
        );
        assert!(
            !generated.rust.contains("\"type\": \"text\""),
            "{}",
            generated.rust
        );
    }

    #[test]
    fn keyword_attribute_on_an_element_also_uses_a_raw_identifier() {
        let source = "fn f() { <label for=\"id\">Name</label>; }";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(
            generated.rust.contains("r#for: \"id\""),
            "{}",
            generated.rust
        );
    }

    #[test]
    fn non_raw_identifiable_keyword_still_uses_the_string_key_form() {
        // `self`/`Self`/`crate`/`super` cannot be raw identifiers at all.
        let source = "fn f() { <div self=\"x\" />; }";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(
            generated.rust.contains("\"self\": \"x\""),
            "{}",
            generated.rust
        );
    }

    /// The `span.start` of the first top-level `mod` item in `parsed`, for
    /// tests that need to key `GenerateOptions::module_paths` (issue #8
    /// fix list step 2: keyed by declaration span, not by name).
    fn first_module_span_start(parsed: &outou_syntax::Parsed) -> u32 {
        parsed
            .file
            .items
            .iter()
            .find_map(|item| match item {
                outou_syntax::ast::Item::Module(module) => Some(module.span.start),
                _ => None,
            })
            .expect("source has a top-level `mod` item")
    }

    #[test]
    fn path_attribute_value_is_not_ifmt_escaped() {
        // MEDIUM-9, issue #6 fix list item 10: `#[path]` is a plain Rust
        // string, not one of `rsx!`'s ifmt format strings; doubling
        // `{`/`}` in the rewritten value (as the ifmt escaper does) would
        // corrupt the path.
        let source = "mod weird;\n";
        let parsed = outou_syntax::parse(source);
        let span_start = first_module_span_start(&parsed);
        let opts = GenerateOptions::new(Uri::new("file:///g.rs"), Uri::new("file:///a.rsx"))
            .with_module_path_at(span_start, "a{b}c\\d.rs");
        let generated = DioxusBackend
            .generate(&parsed, source, Mode::Strict, &opts)
            .expect("generation succeeds");
        assert!(
            generated.rust.contains("#[path = \"a{b}c\\\\d.rs\"]"),
            "{}",
            generated.rust
        );
    }

    #[test]
    fn pathological_attribute_is_not_mistaken_for_path() {
        // MEDIUM-10, issue #6 fix list item 10: a prefix match on
        // `is_path_attribute` silently dropped `#[pathological]`
        // entirely, mistaking it for `#[path]`.
        let source = "#[pathological]\nmod weird;\n";
        let parsed = outou_syntax::parse(source);
        let span_start = first_module_span_start(&parsed);
        let opts = GenerateOptions::new(Uri::new("file:///g.rs"), Uri::new("file:///a.rsx"))
            .with_module_path_at(span_start, "x.rs");
        let generated = DioxusBackend
            .generate(&parsed, source, Mode::Strict, &opts)
            .expect("generation succeeds");
        assert!(
            generated.rust.contains("#[pathological]"),
            "{}",
            generated.rust
        );
        assert!(
            generated.rust.contains("#[path = \"x.rs\"]"),
            "{}",
            generated.rust
        );
    }

    #[test]
    fn doc_comments_are_preserved_verbatim() {
        // LOW-24, issue #6 fix list item 13: "doc comments … preserved
        // verbatim" was ticked in
        // `docs/phase0/issues/06-dioxus-backend-facade.md` with no
        // fixture actually containing a `///` comment (`#[cfg(test)]`
        // was covered, by `components.rsx`, but not this). A `///`
        // fixture now also lives in `examples/phase0-app/src/components.rsx`
        // (`Field`'s doc comment, verified byte-for-byte in
        // `tests/golden/components/expected.rs`); this exercises the
        // same guarantee directly.
        let source = "/// Renders a greeting.\n#[component]\nfn Greeting(name: String) -> Element {\n    <h1>Hello {name}</h1>\n}\n";
        let generated = generate(source, Mode::Strict).expect("generation succeeds");
        assert!(
            generated
                .rust
                .contains("/// Renders a greeting.\n#[component]\nfn Greeting"),
            "{}",
            generated.rust
        );
    }

    #[test]
    fn generation_is_deterministic() {
        let source = "#[component]\nfn App() -> Element {\n    <main class=\"app\"><Greeting name=\"Outou\" /></main>\n}\n";
        let a = generate(source, Mode::Strict).expect("first generation succeeds");
        let b = generate(source, Mode::Strict).expect("second generation succeeds");
        assert_eq!(a.rust, b.rust);
        assert_eq!(a.source_map, b.source_map);
    }

    #[test]
    fn recovery_mode_replaces_a_name_less_element_with_the_placeholder() {
        // A fragment (`<>`) never recovers a tag name at all (grammar §10),
        // unlike e.g. `<div cl` which still knows its name is `div` and
        // lowers as an ordinary (if attribute-less) element.
        let source = "fn App() -> Element {\n    <>\n}\n";
        let generated = generate(source, Mode::Recovery).expect("recovery generation succeeds");
        assert!(generated
            .rust
            .contains("::outou::__private::recovery_element()"));
    }

    #[test]
    fn recovery_mode_still_lowers_a_named_but_unterminated_tag() {
        // `<User` interrupted by the enclosing block's `}` still knows its
        // name (`User`) and its (empty) attribute/child lists, so it
        // lowers as ordinary element syntax rather than the placeholder —
        // Dioxus's own `rsx!` closes an element with a synthesized `}`,
        // never a textual closing tag, so a missing closing tag never
        // prevents reconstruction (see `crate::element::is_broken`'s doc).
        let source = "fn App() -> Element {\n    <User\n}\n";
        let generated = generate(source, Mode::Recovery).expect("recovery generation succeeds");
        assert!(generated.rust.contains("User { }"), "{}", generated.rust);
        assert!(!generated.rust.contains("recovery_element"));
    }

    #[test]
    fn recovery_mode_closes_a_block_that_never_found_its_own_brace() {
        let source = "fn App() -> Element {\n    <div cl";
        let generated = generate(source, Mode::Recovery).expect("recovery generation succeeds");
        assert!(
            generated.rust.trim_end().ends_with('}'),
            "{}",
            generated.rust
        );
        let file = syn_parse(&generated.rust);
        assert!(file.is_ok(), "{:?}: {}", file.err(), generated.rust);
    }

    #[test]
    fn recovery_mode_keeps_the_symbol_for_a_function_with_no_body_at_all() {
        // MEDIUM-14, issue #6 fix list item 7: dropping the item entirely
        // removed `App` from the outline, from completion and from every
        // use site in the file — the opposite of what recovery mode
        // exists for. A placeholder keeps the name resolvable; its body
        // is never executed (`Mode::Recovery` output never reaches
        // `rustc` through `cargo build`).
        let source = "use outou::prelude::*;\n\nfn App(\n";
        let generated = generate(source, Mode::Recovery).expect("recovery generation succeeds");
        assert!(generated.rust.contains("fn App"), "{}", generated.rust);
        assert!(
            generated
                .rust
                .contains("::outou::__private::Element { ::outou::__private::recovery() }"),
            "{}",
            generated.rust
        );
        assert!(generated.rust.contains("use outou::prelude::*;"));
        let file = syn_parse(&generated.rust);
        assert!(file.is_ok(), "{:?}: {}", file.err(), generated.rust);
    }

    /// Minimal Rust-syntax check so recovery-mode tests don't need a `syn`
    /// dev-dependency just for this smoke test (the dedicated recovery
    /// integration test under `tests/` uses `syn` for a thorough check).
    fn syn_parse(rust: &str) -> Result<(), String> {
        let mut depth = 0i32;
        for byte in rust.bytes() {
            match byte {
                b'{' => depth += 1,
                b'}' => depth -= 1,
                _ => {}
            }
            if depth < 0 {
                return Err("unbalanced `}`".to_string());
            }
        }
        if depth == 0 {
            Ok(())
        } else {
            Err(format!("unbalanced braces, depth {depth}"))
        }
    }
}
