// Generated by Outou from file:///src/formatting-crlf-line-endings. Do not edit.
use outou::prelude::*;

#[component]
fn App() -> Element {
    ::outou::__private::rsx! { p { "Hello world", } }
}
