// Generated by Outou from file:///src/formatting-inline-spaces-kept. Do not edit.
use outou::prelude::*;

#[component]
fn App() -> Element {
    ::outou::__private::rsx! { div { p { " a ", }, b { "x", }, " y", } }
}
