// Generated by Outou from file:///src/formatting-single-line-whitespace-only. Do not edit.
use outou::prelude::*;

#[component]
fn App() -> Element {
    ::outou::__private::rsx! { div { p { " ", }, p { }, } }
}
