[package]
name = "outou-backend-dioxus"
description = "Temporary Dioxus execution backend for Outou codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
outou-syntax = { workspace = true }
outou-sourcemap = { workspace = true }
outou-codegen = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
