// Generated by Outou from file:///src/formatting-expression-then-text-newline. Do not edit.
use outou::prelude::*;

#[component]
fn App() -> Element {
    let name = "Outou";

    ::outou::__private::rsx! { div { {name}, "world", } }
}
