// Generated by Outou from file:///src/formatting-blank-lines-dropped. Do not edit.
// `attr={expr}` always lowers an island attribute value as `attr: {expr}`
// (docs/backend-leakage.md row 21): stripping the braces breaks a nested
// `rsx!` island prop (`icon={<span/>}` needs them), and no universal fix
// exists. This never affects a user's own expression lints — only the
// braces this file's codegen itself inserts.
#![allow(unused_braces)]
use outou::prelude::*;

#[component]
fn App() -> Element {
    ::outou::__private::rsx! { p { "Hello world", } }
}
