// Generated by Outou from file:///Users/kiyoshi/Documents/projects/outou-rs/outou/tests/fixtures/workspace/ui-kit/src/shapes/circle.rsx. Do not edit.
use outou::prelude::*;

/// Reached from the crate root through `#[path = "shapes/circle.rsx"]
/// mod circle;`: the module's name (`circle`) does not match its source
/// file's directory (`shapes/`), and its *generated* path still follows
/// the module path convention (`src/.generated/circle.rs`), not the
/// source layout (`crates/outou-modules/README.md`).
#[component]
pub fn Circle(radius: f64) -> Element {
    ::outou::__private::rsx! { div { class: "circle", {radius.to_string()}, } }
}
