// Generated by Outou from file:///Users/kiyoshi/Documents/projects/outou-rs/outou/tests/fixtures/workspace/ui-kit/src/lib.rsx. Do not edit.
use outou::prelude::*;

#[path = "widgets.rs"]
mod widgets;
#[cfg(feature = "extra")]
#[path = "extra.rs"]
mod extra;
#[path = "circle.rs"]
mod circle;
#[path = "../util.rs"]
mod util;

pub use circle::Circle;
pub use widgets::Button;

/// Adds one to `x`.
///
/// A plain Rust doc test (no JSX): `.rsx` files preserve doc comments and
/// their fenced code blocks verbatim through codegen, so this runs under
/// `cargo test --doc -p ui-kit` exactly as if it had been written in a
/// `.rs` file.
///
/// ```
/// assert_eq!(ui_kit::add_one(1), 2);
/// ```
pub fn add_one(x: i32) -> i32 {
    x + 1
}

/// A card built from two other components, one of them (`Button`) from a
/// nested `.rsx` module and one (`Circle`) reached through an explicit
/// `#[path]` into a differently named source file.
#[component]
pub fn Card(title: String) -> Element {
    ::outou::__private::rsx! { div { class: "card", h2 { {title}, }, Circle { radius: util::double(1) as f64, }, Button { label: "OK", }, } }
}

#[cfg(test)]
mod tests {
    #[test]
    fn plain_rust_tests_still_run_in_a_library_crate() {
        assert_eq!(super::add_one(1), 2);
    }
}
