// Generated by Outou from file:///Users/kiyoshi/Documents/projects/outou-rs/outou/tests/fixtures/workspace/ui-kit/src/widgets.rsx. Do not edit.
use outou::prelude::*;

#[path = "widgets/button.rs"]
mod button;

pub use button::Button;

/// A toolbar containing one `Button`, from the nested `button` module.
#[component]
pub fn Toolbar() -> Element {
    ::outou::__private::rsx! { div { class: "toolbar", Button { label: "Toolbar", }, } }
}
