// Generated by Outou from file:///src/formatting-attribute-escapes. Do not edit.
use outou::prelude::*;

#[component]
fn App() -> Element {
    ::outou::__private::rsx! { p { title: "tab\there\nline \\ and \"quote\"", "note", } }
}
