// Generated by Outou from file:///src/components. Do not edit.
use outou::prelude::*;

#[derive(Debug, Clone, PartialEq)]
pub struct User {
    pub name: String,
}

/// Formats a user's initial for a compact badge.
///
/// A plain Rust doc test (no JSX): `.rsx` files preserve doc comments and
/// their fenced code blocks verbatim through codegen (issue #10). This
/// one, however, cannot actually run under `cargo test --doc` here: this
/// crate is `[[bin]]`-only (ADR 0009's application layout), and
/// `cargo test --doc` requires a `[lib]` target to link the doctest
/// against — a Cargo constraint independent of JSX or Outou, and a
/// genuine Phase 0 finding (`crates/outou-cli/README.md`). Doc tests
/// containing JSX are not required either way (`TODO(phase0)`);
/// `tests/fixtures/workspace/ui-kit` (a library crate) is where this
/// same doc-comment shape is exercised for real, under
/// `cargo test --doc -p ui-kit`.
///
/// ```
/// assert_eq!(1 + 1, 2);
/// ```
pub fn initial(user: &User) -> Option<char> {
    user.name.chars().next()
}

#[component]
pub fn UserCard(user: User) -> Element {
    ::outou::__private::rsx! { div { class: "user-card", {user.name}, } }
}

/// A labeled form field. `type` is a JSX attribute name that happens to
/// be a Rust keyword (grammar §5); the component's own parameter must
/// therefore be written as the raw identifier `r#type` (issue #6 fix
/// list item 3, HIGH-3: Dioxus's raw string-key syntax for such a name
/// only exists for elements, not components, so a keyword prop is only
/// representable via `r#type`).
#[component]
pub fn Field(label: String, r#type: String) -> Element {
    ::outou::__private::rsx! { div { class: "field", label { r#for: "id", {label}, }, input { id: "id", r#type: r#type.clone(), }, } }
}

/// A second card, added as a Gate 3 regression fixture (issue #9 review,
/// H3): `MyProps` is an ordinary user struct, not anything the backend
/// generated, but its name happens to end in `Props` — exactly the shape
/// `crate::translate::looks_like_generated_name`'s bare heuristic used to
/// (wrongly) treat as backend vocabulary, blanking hover on both the
/// `config` parameter and the type itself.
#[derive(Debug, Clone, PartialEq)]
pub struct MyProps {
    pub title: String,
}

#[component]
pub fn Card2(config: MyProps) -> Element {
    ::outou::__private::rsx! { div { class: "card2", {config.title}, } }
}

#[cfg(test)]
mod tests {
    #[test]
    fn plain_rust_tests_still_run() {
        assert_eq!(1 + 1, 2);
    }
}
