// Generated by Outou from file:///src/components. Do not edit.
// `attr={expr}` always lowers an island attribute value as `attr: {expr}`
// (docs/backend-leakage.md row 21): stripping the braces breaks a nested
// `rsx!` island prop (`icon={<span/>}` needs them), and no universal fix
// exists. This never affects a user's own expression lints — only the
// braces this file's codegen itself inserts.
#![allow(unused_braces)]
use outou::prelude::*;

#[derive(Debug, Clone, PartialEq)]
pub struct User {
    pub name: String,
}

#[component]
pub fn UserCard(user: User) -> Element {
    ::outou::__private::rsx! { div { class: "user-card", {user.name}, } }
}

/// A labeled form field. `type` is a JSX attribute name that happens to
/// be a Rust keyword (grammar §5); the component's own parameter must
/// therefore be written as the raw identifier `r#type` (issue #6 fix
/// list item 3, HIGH-3: Dioxus's raw string-key syntax for such a name
/// only exists for elements, not components, so a keyword prop is only
/// representable via `r#type`).
#[component]
pub fn Field(label: String, r#type: String) -> Element {
    ::outou::__private::rsx! { div { class: "field", label { r#for: "id", {label}, }, input { id: "id", r#type: {r#type.clone()}, }, } }
}

#[cfg(test)]
mod tests {
    #[test]
    fn plain_rust_tests_still_run() {
        assert_eq!(1 + 1, 2);
    }
}
