// Generated by Outou from file:///src/main. Do not edit.
use outou::prelude::*;

#[path = "components.rs"]
mod components;

use components::{Field, UserCard};

#[component]
fn Greeting(name: String) -> Element {
    ::outou::__private::rsx! { h1 { "Hello ", {name}, } }
}

#[component]
fn TagList(tags: Vec<String>) -> Element {
    ::outou::__private::rsx! { ul { class: "tags", {tags.iter().map(|tag| ::outou::__private::rsx! { li { key: "{tag.clone()}", {tag.clone()}, } })}, } }
}

#[component]
fn App() -> Element {
    let user = load_user();
    let tags = vec!["rust".to_string(), "jsx".to_string(), "phase0".to_string()];

    ::outou::__private::rsx! { main { class: "app", Greeting { name: "Outou", }, {
            if user.is_some() {
                ::outou::__private::rsx! { UserCard { user: user.unwrap(), } }
            } else {
                ::outou::__private::rsx! { p { "No user", } }
            }
        }, TagList { tags: tags, }, form { Field { label: "Name", r#type: "text", }, }, } }
}

fn load_user() -> Option<components::User> {
    Some(components::User { name: "Outou".to_string() })
}

fn main() {
    let _ = App;
}
