// Generated by Outou from file:///Users/kiyoshi/Documents/projects/outou-rs/outou/tests/fixtures/workspace/ui-kit/src/widgets/button.rsx. Do not edit.
use outou::prelude::*;

#[component]
pub fn Button(label: String) -> Element {
    ::outou::__private::rsx! { button { {label}, } }
}
